apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: profile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: adelowo/profile-generator
        ports:
          - containerPort: 6200
